python:
- 3.12
python_impl:
- cpython
numpy:
- 1.16
MACOSX_SDK_VERSION:            # [osx and x86_64]
- 11.0                         # [osx and x86_64]
build_type:
- release
channel_sources:
- e8035669acarmv7,conda-forge
channel_targets:
- e8035669acarmv7 main
zip_keys:
- build_type
- channel_targets
docker_image:
- e8035669/linux-anvil-armv7l  # [os.environ.get("BUILD_PLATFORM") == "linux-armv7l"]
