build_platform:
  linux_armv7l: linux_armv7l
conda_forge_output_validation: true
provider:
  linux_armv7l: azure
  linux_64: None
  osx_64: None
  win_64: None
  linux_ppc64le: None
  linux_aarch64: None
test_on_native_only: true
bot:
  abi_migration_branches:
  - 3.7
  - 3.8
  - 3.9
azure:
  store_build_artifacts: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
remote_ci_setup: e8035669acarmv7::conda-forge-ci-setup=3       # https://github.com/conda/conda-build/issues/4750
channels:
  sources:
  - e8035669acarmv7
  - conda-forge
  targets:
  - [e8035669acarmv7, main]
channel_priority: flexible

